print("hi "+input("what is your name :")+"!"+"\nwelcome to the BAND NAME CREATER APPLICATION...")
print("tell me about yourself..")
city=input("your city : ")
last_name=input("your last name : ")
print(f"your band name is : "+ city+" " +last_name +" BAND")